### ISSUE TITLE
Possible bug in utf8ToUnicode()

### ISSUE THREAD

**Issue by marcochiodo** [instasent/sms-counter-php#10]
Hi,

It seems that the utf8ToUnicode () function returns an unexpected result when there are more special utf8 characters in the string such as emojii.

Considering the following character: "😎" ( https://emojipedia.org/smiling-face-with-sunglasses/ )

When the function is called, passing a string containing a single emojii, it returns an array with a single integer value 2008.

When instead the string contains 2 emojii, the function returns an array containing 3 integer values: 2008, 944, 2008

### code snipped
![immagine](https://user-images.githubusercontent.com/828361/58160996-c045c700-7c7f-11e9-9674-e145739b39a3.png)

### output
![immagine](https://user-images.githubusercontent.com/828361/58161053-d94e7800-7c7f-11e9-93a1-2a8943ae0036.png)

**Comment by juliangut** [comment]
Thanks @marcochiodo, it's been fixed
