### ISSUE TITLE
Please confirm if wooblecode was renamed to instasent ?

### ISSUE THREAD

**Issue by acpmasquerade** [instasent/sms-counter-php#18]
Hi, 
I am the original maintainer of sms-counter-php. After maintaining for some years, I had updated the readme in my repo with a cross link to the repo github.com/wooblecode/sms-counter-php. 

The repo is now redirecting to this repo. Please confirm the change so that I can update the original repo with the meta link to this updated repo.

Regards,

**Comment by luishdez** [comment]
That's correct I did move it from wobblecode to instasent.

**Comment by acpmasquerade** [comment]
Thanks. 
Information has been updated.
