### ISSUE TITLE
$text = utf8ToUnicode($text);

### ISSUE THREAD

**Issue by shatilov** [instasent/sms-counter-php#7]
https://github.com/instasent/sms-counter-php/blob/0b4f0308374429c1d56b9ab38f831917b3f5da9f/SMSCounter.php#L176

maybe $text =  $this->utf8ToUnicode($text);

**Comment by grzegorztomasiak** [comment]
There is more inconsistency in the code just than this.

**Comment by luishdez** [comment]
Thanks @shatilov we'll fix that. @grzegorztomasiak Please let us know if you find any other bug.

Any PR is welcomed.
